fume/urls.py
from typing import List, Union

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path
from django.urls.resolvers import URLPattern, URLResolver

from . import views


urlpatterns: List[Union[URLPattern, URLResolver]] = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.index),
    re_path(r'^tags/', include(('tags.urls', 'tags'), namespace='tags')),
    re_path(r'^games/', include(('games.urls', 'games'), namespace='games')),
    re_path(r'^purchase/', include(
        ('purchase.urls', 'purchase'),namespace='purchase'
    )),
    re_path(r'^member/', include(('member.urls', 'member'), namespace='member')),
    re_path(r'^accounts/', include(('member.urls', 'member'), namespace='member')),
    re_path(r'^oauth/', include(
        ('social_django.urls', 'social'), namespace='social'
    )),
    re_path(r'^reviews/', include(
        ('reviews.urls', 'reviews'), namespace = 'reviews'
    )),
]

if settings.DEBUG is True:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

games/urls.py
from typing import List, Union

from django.urls import re_path
from django.urls.resolvers import URLPattern, URLResolver

from .models import Game
from . import views


genres: str = '|'.join(
    [choice[1].lower() for choice in Game._meta.get_field('genre').choices]
)

urlpatterns: List[Union[URLPattern, URLResolver]] = [
    re_path(r'^(?P<gameID>[0-9]+)/$', views.game, name='game'),
    re_path(r'^(?P<gameID>[0-9]+)/tag$', views.tag, name='tag'),
    re_path(r'^(?P<gameID>[0-9]+)/tag/add$', views.add_tag, name='add_tag'),
    re_path(r'^genres/$', views.genres, name='genres'),
    re_path(r'^genres/(?P<genre>\w+)/$', views.genre, name='genre'),
    re_path(r'^purchased/$', views.purchased, name='purchased')
]

member/urls.py
from typing import List, Union

from django.conf.urls import include
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.urls.resolvers import URLPattern, URLResolver

from .views import signup


urlpatterns: List[Union[URLPattern, URLResolver]] = [
    re_path(r'^signup/$', signup, name='signup'),
    re_path(
        r'^login/$', auth_views.LoginView.as_view(),
        {'template_name': 'member/login.html'},
        name='login',
    ),
    re_path(
        r'^logout/$',
        auth_views.LogoutView.as_view(),
        {'template_name': 'member/logout.html'},
        name='logout',
    ),
    re_path(
        r'^password_reset/$',
        auth_views.PasswordResetView.as_view(),
        {
            'template_name': 'member/password_reset.html',
            'email_template_name': 'member/password_reset_email.html',
            'post_reset_redirect': '/member/password_reset_done/',
        },
        name='password_reset',
    ),
    re_path(
        r'^password_reset_done/$',
        auth_views.PasswordResetDoneView.as_view(),
        {'template_name': 'member/password_reset_done.html'},
	    name='password_reset_done',
    ),
    re_path(
        r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(),
        {
            'template_name': 'member/password_reset_confirm.html',
            'post_reset_redirect': '/member/password_reset_complete/',
        },
        name='password_reset_confirm',
    ),
    re_path(
        r'^password_reset_complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        {'template_name': 'member/password_reset_complete.html'},
        name='password_reset_complete',
    ),
]

tags/urls.py
from typing import List, Union

from django.urls import re_path
from django.urls.resolvers import URLPattern, URLResolver

from . import views


urlpatterns: List[Union[URLPattern, URLPattern]] = [
    re_path(r'^(?P<game_id>[0-9]+)/$', views.tag, name='tag'),
    re_path(r'^(?P<game_id>[0-9]+)/add/$', views.add, name='add'),
    re_path(
        r'^view/(?P<label>\w+.*)/$',
        views.view_games_by_tag,
        name='view_games_by_tag',
    ),
    re_path(r'^view_all_tags/$', views.view_all_tags, name='view_all_tags'),
]

tags/fake/member/models.py
from __future__ import annotations

from datetime import date

from django.db import models


class Member(models.Model):
    username: models.CharField = models.CharField(max_length=50)
    password: models.CharField = models.CharField(max_length=30)
    nickname: models.CharField = models.CharField(max_length=30)
    email: models.CharField = models.CharField(max_length=100)
    total_amount: models.FloatField = models.FloatField()

    @classmethod
    def create(
        cls, username: str, password: str, nickname: str, email: str,
        payment_method: PaymentMethod
    ) -> Member:
        member = cls(
            username=username, password=password, nickname=nickname,
            email=email, total_amount=0, paymentMethod = payment_method
        )
        return member
        
    def get_rewards(self) -> int:
        rewards = Reward.objects.filter(member=self)
        for reward in rewards:
            if reward.expiration_date < date.today():
                Reward.objects.get(
                    expiration_date=reward.expiration_date, member=self
                ).delete()
        return len(rewards)

    def use_rewards(self, number: int) -> None:
        rewards = self.rewards.all()
        for reward in rewards:
            if reward.expiration_date < date.today():
                reward.delete()
        used_rewards = rewards.order_by('expiration_date')[:number]
        for reward in used_rewards:
            reward.delete()
    
    def accumulate_spending(self, amount: float) -> None:
        self.total_amount += amount
        while self.total_amount > Reward.THRESHOLD:
            new_reward = Reward.create(self, date.today())
            new_reward.save()
            self.total_amount -= Reward.THRESHOLD
        self.save()


class PaymentMethod(models.Model):
    account_number: models.IntegerField = models.IntegerField()
    member: models.OneToOneField = models.OneToOneField(
        Member, on_delete=models.CASCADE, related_name='payment_method')

    @classmethod
    def create(cls, account_number: int, member: Member) -> PaymentMethod:
        return cls(account_number=account_number, member=member)


class Reward(models.Model):
    THRESHOLD: int = 100
    
    expiration_date: models.DateField = models.DateField()
    member: models.ForeignKey = models.ForeignKey(
        Member, on_delete=models.CASCADE, related_name='rewards')
    
    @classmethod
    def create(cls, member: Member, expiration_date: date) -> Reward:
        return cls(expiration_date=expiration_date, member=member)

tags/models.py
from __future__ import annotations

from typing import List

from django.db import models

from games.models import Game
from member.models import Member


class TagManager(models.Manager):

	def get_tags_of_game(
		self, game: Game, order: str = 'Arbitrary'
	) -> List[TagItem]:
		tag_items = TagItem.objects.filter(game=game)
		tags = set()
		for tag_item in tag_items:
			tags.add(tag_item.tag)
		tags = list(tags)
		if (order == 'Lexicographical'):
			tags.sort(key=lambda tag: tag.label)
		return tags

	def get_games_by_tag(
		self, tag: 'Tag', order: str = 'Arbitrary'
	) -> List[Game]:
		tag_items = TagItem.objects.filter(tag=tag)
		games = set()
		for tag_item in tag_items:
			games.add(tag_item.game)
		games = list(games)
		return games

class Tag(models.Model):
	label: models.TextField = models.TextField(max_length=100)
	objects: TagManager = TagManager()

	@classmethod
	def create(cls, label: str) -> Tag:
		return cls(label=label)


class TagItem(models.Model):
	tag: models.ForeignKey = models.ForeignKey(Tag, on_delete=models.CASCADE)
	tagger: models.ForeignKey = models.ForeignKey(
		Member, on_delete=models.CASCADE)
	game: models.ForeignKey = models.ForeignKey(
		Game, on_delete=models.CASCADE, related_name='tag_items')

	@classmethod
	def create(cls, tag: Tag, tagger: Member, game: Game) -> TagItem:
		return cls(tag=tag, tagger=tagger, game=game)

tags/fake/member/views.py
from django.shortcuts import render

tags/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse

from games.models import Game
from member.models import Member
from .models import TagItem, Tag


def tag(request: HttpRequest, game_id: int) -> HttpResponse:
    game = Game.objects.get(pk=game_id)
    member = request.user.member
    tag_items = game.tag_items.all()
    tags = Tag.objects.get_tags_of_game(game)
    context = {'member':member, 'game':game, 'tags':tags}
    return render(request, 'tags/tag.html', context)


def add(request: HttpRequest, game_id: int) -> HttpResponse:
    game = Game.objects.get(pk=game_id)
    member = request.user.member
    label = request.GET.get('tag')
    tag = Tag.objects.get_or_create(label=label)[0]
    tag_item = TagItem.create(tag, member, game)
    tag_item.save()
    return redirect('games:game', gameID=game_id)


def view_games_by_tag(request: HttpRequest, label: str) -> HttpResponse:
    tag = Tag.objects.get(label=label)
    games = Tag.objects.get_games_by_tag(tag)
    context = {'games': games}
    return render(request, 'tags/view_games_by_tag.html', context)


def view_all_tags(request: HttpRequest) -> HttpResponse:
    tags = Tag.objects.all()
    context = {'tags':tags}
    return render(request, 'tags/tags.html', context)

tags/templates/tags/tag.html
<p>Hello, {{ member }}</p>
<p>Tagging game {{ game }}</p>
<form action="{% url 'tags:add' game.pk %}">
	Add tag:
	<br>  
	<input type="text" name="tag">
	<br>
	<input type="submit" value="Add">
</form>
<ul>
	{% for tag in tags %}
		<li>{{ tag.label }}</li>
	{% endfor %}
</ul>
	

tags/templates/tags/tags.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- load MUI -->
    <link href="//cdn.muicss.com/mui-0.9.15/css/mui.min.css" rel="stylesheet" type="text/css" />
    <link href="{% static "/tags/view_game.css" %}" rel = "stylesheet" type = "text/css"/>
    <script src="//cdn.muicss.com/mui-0.9.15/js/mui.min.js"></script>
	  </head>
	  <body>

	  <header class="mui-appbar mui--z1">
      <div class="mui-container">
        <table width="100%">
          <tr class="mui--appbar-height">
            <td class="mui--text-title"><a style = “color:white;" href="/">FUME</a></td>
            <td align="left">
              <ul class="mui-list--inline mui--text-body2">
                {% if user.is_authenticated %}

                <li><a href="{% url 'member:logout' %}">Log Out</a></li>
                <li><a href="{% url 'games:purchased' %}">Games purchased</a></li>
                {% else %}
                <li><a href="{% url 'member:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'member:login' %}">Log In</a></li>
                {% endif %}
                <li><a href="{% url 'games:genres' %}">Genres</a></li>
                <li><a href = "{% url 'tags:view_all_tags'%}">Tags</a></li>
              </ul>
            </td>
          </tr>
        </table>
      </div>
    </header>
    <div class = "mui-container">
    <div class = "mui-panel">
	{%for tag in tags%}
		<li class = "tagli"><a class="tagButton purchaseButton mui-btn mui-btn--primary mui-btn--raised" href="{% url 'tags:view_games_by_tag' tag.label %}">{{ tag.label }}</a></li>
	{%endfor%}
	</div>

	</body>
	</html>

tags/templates/tags/view_games_by_tag.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- load MUI -->
    <link href="//cdn.muicss.com/mui-0.9.15/css/mui.min.css" rel="stylesheet" type="text/css" />
    <link href="{% static "/tags/view_game.css" %}" rel = "stylesheet" type = "text/css"/>
    <script src="//cdn.muicss.com/mui-0.9.15/js/mui.min.js"></script>
	  </head>
	  <body>
	  <header class="mui-appbar mui--z1">
      <div class="mui-container">
        <table width="100%">
          <tr class="mui--appbar-height">
            <td class="mui--text-title"><a style = “color:white;" href="/">FUME</a></td>
            <td align="left">
              <ul class="mui-list--inline mui--text-body2">
                {% if user.is_authenticated %}

                <li><a href="{% url 'member:logout' %}">Log Out</a></li>
                <li><a href="{% url 'games:purchased' %}">Games purchased</a></li>
                {% else %}
                <li><a href="{% url 'member:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'member:login' %}">Log In</a></li>
                {% endif %}
                <li><a href="{% url 'games:genres' %}">Genres</a></li>
                <li><a href = "{% url 'tags:view_all_tags'%}">Tags</a></li>
              </ul>
            </td>
          </tr>
        </table>
      </div>
    </header>
	  <div class="mui-container">
	  <div class = "mui-panel">
		
      {% for game in games %}
    <div class = "mui-panel">
        <div style = "float:left">
        <img src="{{ game.thumbnail.url }}" height="90" width="160">
        <h2><b>{{ game.get_genre_display }}</b> <a href="{% url 'games:game' game.id %}">{{ game.title }}</a></h2>
        <h3>{{ game.description }}</h3>
        <ul>
            {% for item in game.items.all %}
                <li>{{ item.get_platform_display }} - $ {{ item.price }}</li>
            {% endfor %}
        </ul>
        </div>
        <div>
        {% regroup game.tag_items.all|dictsort:'tag.label' by tag.label as tags %}
        {% for tag in tags %}
        <li class = "tagli" style = "display:inline">
            <a class="tagButton purchaseButton mui-btn mui-btn--primary mui-btn--raised" href="{% url 'tags:view_games_by_tag' tag.grouper %}">{{ tag.grouper }}</a></li>
        {% endfor %}
        </div>
    </div>
    {% endfor %}
		</div>
	</div>
	</body>