fume/urls.py
from typing import List, Union

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path
from django.urls.resolvers import URLPattern, URLResolver

from . import views


urlpatterns: List[Union[URLPattern, URLResolver]] = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', views.index),
    re_path(r'^tags/', include(('tags.urls', 'tags'), namespace='tags')),
    re_path(r'^games/', include(('games.urls', 'games'), namespace='games')),
    re_path(r'^purchase/', include(
        ('purchase.urls', 'purchase'),namespace='purchase'
    )),
    re_path(r'^member/', include(('member.urls', 'member'), namespace='member')),
    re_path(r'^accounts/', include(('member.urls', 'member'), namespace='member')),
    re_path(r'^oauth/', include(
        ('social_django.urls', 'social'), namespace='social'
    )),
    re_path(r'^reviews/', include(
        ('reviews.urls', 'reviews'), namespace = 'reviews'
    )),
]

if settings.DEBUG is True:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

games/urls.py
from typing import List, Union

from django.urls import re_path
from django.urls.resolvers import URLPattern, URLResolver

from .models import Game
from . import views


genres: str = '|'.join(
    [choice[1].lower() for choice in Game._meta.get_field('genre').choices]
)

urlpatterns: List[Union[URLPattern, URLResolver]] = [
    re_path(r'^(?P<gameID>[0-9]+)/$', views.game, name='game'),
    re_path(r'^(?P<gameID>[0-9]+)/tag$', views.tag, name='tag'),
    re_path(r'^(?P<gameID>[0-9]+)/tag/add$', views.add_tag, name='add_tag'),
    re_path(r'^genres/$', views.genres, name='genres'),
    re_path(r'^genres/(?P<genre>\w+)/$', views.genre, name='genre'),
    re_path(r'^purchased/$', views.purchased, name='purchased')
]

member/urls.py
from typing import List, Union

from django.conf.urls import include
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.urls.resolvers import URLPattern, URLResolver

from .views import signup


urlpatterns: List[Union[URLPattern, URLResolver]] = [
    re_path(r'^signup/$', signup, name='signup'),
    re_path(
        r'^login/$', auth_views.LoginView.as_view(),
        {'template_name': 'member/login.html'},
        name='login',
    ),
    re_path(
        r'^logout/$',
        auth_views.LogoutView.as_view(),
        {'template_name': 'member/logout.html'},
        name='logout',
    ),
    re_path(
        r'^password_reset/$',
        auth_views.PasswordResetView.as_view(),
        {
            'template_name': 'member/password_reset.html',
            'email_template_name': 'member/password_reset_email.html',
            'post_reset_redirect': '/member/password_reset_done/',
        },
        name='password_reset',
    ),
    re_path(
        r'^password_reset_done/$',
        auth_views.PasswordResetDoneView.as_view(),
        {'template_name': 'member/password_reset_done.html'},
	    name='password_reset_done',
    ),
    re_path(
        r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(),
        {
            'template_name': 'member/password_reset_confirm.html',
            'post_reset_redirect': '/member/password_reset_complete/',
        },
        name='password_reset_confirm',
    ),
    re_path(
        r'^password_reset_complete/$',
        auth_views.PasswordResetCompleteView.as_view(),
        {'template_name': 'member/password_reset_complete.html'},
        name='password_reset_complete',
    ),
]

tags/urls.py
from typing import List, Union

from django.urls import re_path
from django.urls.resolvers import URLPattern, URLResolver

from . import views


urlpatterns: List[Union[URLPattern, URLPattern]] = [
    re_path(r'^(?P<game_id>[0-9]+)/$', views.tag, name='tag'),
    re_path(r'^(?P<game_id>[0-9]+)/add/$', views.add, name='add'),
    re_path(
        r'^view/(?P<label>\w+.*)/$',
        views.view_games_by_tag,
        name='view_games_by_tag',
    ),
    re_path(r'^view_all_tags/$', views.view_all_tags, name='view_all_tags'),
]

member/models.py
from __future__ import annotations

import datetime
from typing import List, TYPE_CHECKING

from django.db import models
from django.contrib.auth.models import User
from django.core.mail import send_mail

if TYPE_CHECKING:
    from purchase.models import PurchaseRecord


class Member(models.Model):
    user: models.OneToOneField = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='member')
    nickname: models.CharField = models.CharField(max_length=100)
    avatar: models.ImageField = models.ImageField(
        upload_to='images/avatars', default='images/avatars/default.jpg')
    accumulated_spending: models.IntegerField = models.IntegerField(default=28)

    @classmethod
    def create(cls, user: User, nickname: str) -> Member:
        return cls.objects.create(user=user, nickname=nickname)

    def get_number_of_rewards(self) -> int:
        return self.rewards.filter(
            expiration_date__gte=datetime.datetime.now()).count()

    def get_payment_method(self) -> PaymentMethod:
        return self.payment_method

    def get_rewards(self) -> List['Reward']:
        return self.rewards.filter(
            expiration_date__gte=datetime.datetime.now()
        ).order_by('expiration_date')

    def use_rewards(self, number: int) -> None:
        expiredRewards = self.rewards.filter(
            expiration_date__lt=datetime.datetime.now())
        usedRewards = self.rewards.filter(
            expiration_date__gte=datetime.datetime.now()
        ).order_by('expiration_date')[:number]
        for reward in list(expiredRewards) + list(usedRewards):
            reward.delete()

    def accumulate_spending(self, amount: float) -> None:
        self.accumulated_spending = self.accumulated_spending + amount
        print(self.accumulated_spending)
        number_of_new_rewards = 0
        while self.accumulated_spending >= Reward.THRESHOLD:
            number_of_new_rewards += 1
            Reward.create(
                member=self,
                date=datetime.datetime.now() + datetime.timedelta(days=120),
            )
            self.accumulated_spending -= Reward.THRESHOLD
        if number_of_new_rewards > 0:
            send_mail(
                'New Rewards',
                f'You got {number_of_new_rewards} new rewards.',
                'noreply@fume.com',
                [self.user.email],
                fail_silently=True,
            )
        self.save()

    def get_purchase_history(self) -> List[PurchaseRecord]:
        return self.purchase_records

    def __str__(self) -> str:
        return self.nickname


class PaymentMethod(models.Model):
    account_number: models.IntegerField = models.IntegerField()
    member: models.OneToOneField = models.OneToOneField(
        Member, on_delete = models.CASCADE, related_name='payment_method')

    @classmethod
    def create(cls, account_number: int, member: Member) -> PaymentMethod:
        return cls.objects.create(account_number=account_number, member=member)

    def get_account(self) -> int:
        return self.account_number

    def __str__(self) -> str:
        return self.member.nickname


class Reward(models.Model):
    THRESHOLD: int = 100

    expiration_date: models.DateTimeField = models.DateTimeField()
    member: models.ForeignKey = models.ForeignKey(
        Member, on_delete = models.CASCADE, related_name='rewards')

    @classmethod
    def create(cls, member: Member, date: datetime.date) -> Reward:
        return cls.objects.create(member=member, expiration_date=date)

    def __str__(self) -> str:
        return (
            f'{self.member.nickname}'
            f' {self.expiration_date.strftime("%Y-%m-%d %H:%M:%S")}'
        )

purchase/fake/member/models.py
from __future__ import annotations

from datetime import date
from typing import Any

from django.db import models


class Member(models.Model):
    username: models.CharField = models.CharField(max_length=50)
    password: models.CharField = models.CharField(max_length=30)
    nickname: models.CharField = models.CharField(max_length=30)
    email: models.CharField = models.CharField(max_length=100)
    total_amount: models.FloatField = models.FloatField()

    @classmethod
    def create(
        cls, username: str, password: str, nickname: str, email: str,
        payment_method: PaymentMethod
    ) -> Member:
        member = cls(
            username=username, password=password, nickname=nickname,
            email=email, total_amount=0, paymentMethod=payment_method
        )
        return member
        
    def get_rewards(self) -> int:
        rewards = Reward.objects.filter(member=self)
        for reward in rewards:
            if reward.expiration_date < date.today():
                Reward.objects.get(
                    expiration_date=reward.expiration_date, member=self
                ).delete()
        return len(rewards)

    def use_rewards(self, number: int) -> None:
        rewards = self.rewards.all()
        for reward in rewards:
            if reward.expiration_date < date.today():
                reward.delete()
        used_rewards = rewards.order_by('expiration_date')[:number]
        for reward in used_rewards:
            reward.delete()
    
    def accumulate_spending(self, amount: int) -> None:
        self.total_amount += amount
        while self.total_amount > Reward.THRESHOLD:
            new_reward = Reward.create(self, date.today())
            new_reward.save()
            self.total_amount -= Reward.THRESHOLD
        self.save()


class PaymentMethod(models.Model):
    account_number: models.IntegerField = models.IntegerField()
    member: models.OneToOneField = models.OneToOneField(
        Member, on_delete = models.CASCADE, related_name='payment_method'
    )

    @classmethod
    def create(cls, account_number: int, member: Member) -> PaymentMethod:
        return cls(account_number=account_number, member=member)


class Reward(models.Model):
    THRESHOLD: int = 100
    
    expiration_date: models.DateField = models.DateField()
    member: models.ForeignKey = models.ForeignKey(
        Member, on_delete=models.CASCADE, related_name='rewards')
    
    @classmethod
    def create(cls, member: Member, expiration_date: date) -> Reward:
        return cls(expiration_date=expiration_date, member=member)

tags/fake/member/models.py
from __future__ import annotations

from datetime import date

from django.db import models


class Member(models.Model):
    username: models.CharField = models.CharField(max_length=50)
    password: models.CharField = models.CharField(max_length=30)
    nickname: models.CharField = models.CharField(max_length=30)
    email: models.CharField = models.CharField(max_length=100)
    total_amount: models.FloatField = models.FloatField()

    @classmethod
    def create(
        cls, username: str, password: str, nickname: str, email: str,
        payment_method: PaymentMethod
    ) -> Member:
        member = cls(
            username=username, password=password, nickname=nickname,
            email=email, total_amount=0, paymentMethod = payment_method
        )
        return member
        
    def get_rewards(self) -> int:
        rewards = Reward.objects.filter(member=self)
        for reward in rewards:
            if reward.expiration_date < date.today():
                Reward.objects.get(
                    expiration_date=reward.expiration_date, member=self
                ).delete()
        return len(rewards)

    def use_rewards(self, number: int) -> None:
        rewards = self.rewards.all()
        for reward in rewards:
            if reward.expiration_date < date.today():
                reward.delete()
        used_rewards = rewards.order_by('expiration_date')[:number]
        for reward in used_rewards:
            reward.delete()
    
    def accumulate_spending(self, amount: float) -> None:
        self.total_amount += amount
        while self.total_amount > Reward.THRESHOLD:
            new_reward = Reward.create(self, date.today())
            new_reward.save()
            self.total_amount -= Reward.THRESHOLD
        self.save()


class PaymentMethod(models.Model):
    account_number: models.IntegerField = models.IntegerField()
    member: models.OneToOneField = models.OneToOneField(
        Member, on_delete=models.CASCADE, related_name='payment_method')

    @classmethod
    def create(cls, account_number: int, member: Member) -> PaymentMethod:
        return cls(account_number=account_number, member=member)


class Reward(models.Model):
    THRESHOLD: int = 100
    
    expiration_date: models.DateField = models.DateField()
    member: models.ForeignKey = models.ForeignKey(
        Member, on_delete=models.CASCADE, related_name='rewards')
    
    @classmethod
    def create(cls, member: Member, expiration_date: date) -> Reward:
        return cls(expiration_date=expiration_date, member=member)

member/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignupForm(forms.Form):
	username: forms.CharField = forms.CharField()
	password: forms.CharField = forms.CharField(widget=forms.PasswordInput)
	email: forms.EmailField = forms.EmailField()
	nickname: forms.CharField = forms.CharField()

	def clean_username(self) -> str:
		username = self.cleaned_data['username']
		if User.objects.filter(username=username).exists():
			raise ValidationError("Username taken")
		return username

	def clean_email(self) -> str:
		email = self.cleaned_data['email']
		if User.objects.filter(email=email).exists():
			raise ValidationError("Email used")
		return email
		

member/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.backends import ModelBackend

from .forms import SignupForm
from .models import Member, PaymentMethod

def signup(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        return render(request, 'member/signup.html', {'form': SignupForm()})
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            User.objects.create_user(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password'],
            )
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )
            if user:
                login(request, user)
                member = Member.create(
                    user=user, nickname=form.cleaned_data['nickname'])
                PaymentMethod.create(account_number=user.id, member=member)
                return HttpResponseRedirect('/')
            return render(request, 'member/signup.html', {'form': form})
        else:
            return render(request, 'member/signup.html', {'form': form})

tags/fake/member/views.py
from django.shortcuts import render

member/templates/member/password_reset.html
<h1>Reset Password</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Reset Password"/>
</form>

member/templates/member/password_reset_complete.html
<p>Your password has been set.  You may go ahead and log in now.</p>
<p><a href="{% url 'member:login' %}">Log In</a></p>

member/templates/member/password_reset_confirm.html
{% if validlink %}

    <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

    <form method="post">{% csrf_token %}
        <p class="form-row field-password1">
            {{ form.new_password1.errors }}
            <label for="id_new_password1">New password:</label>
            {{ form.new_password1 }}
        </p>
        <p class="form-row field-password2">
            {{ form.new_password2.errors }}
            <label for="id_new_password2">Confirm password:</label>
            {{ form.new_password2 }}
        </p>
        <input type="submit" value="Change my password" />
    </form>

{% else %}

    <p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset."</p>

{% endif %}

member/templates/member/password_reset_done.html
<p>We've e-mailed you instructions for setting your password to the e-mail address you submitted.</p>
<p>You should be receiving it shortly.</p>

<a href="/">Home</a>

member/templates/member/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'member:password_reset_confirm' uidb64=uid token=token %}

member/templates/member/purchased.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- load MUI -->
    <link href="//cdn.muicss.com/mui-0.9.15/css/mui.min.css" rel="stylesheet" type="text/css" />
    <link href="{% static "game.css" %}" rel = "stylesheet" type = "text/css"/>
    <script src="//cdn.muicss.com/mui-0.9.15/js/mui.min.js"></script>
	  </head>
	  <body>

	  <header class="mui-appbar mui--z1">
      <div class="mui-container">
        <table width="100%">
          <tr class="mui--appbar-height">
            <td class="mui--text-title"><a style = “color:white;" href="/">FUME</a></td>
            <td align="left">
              <ul class="mui-list--inline mui--text-body2">
                {% if user.is_authenticated %}

                <li><a href="{% url 'member:logout' %}">Log Out</a></li>
                <li><a href="{% url 'games:purchased' %}">Games purchased</a></li>
                {% else %}
                <li><a href="{% url 'member:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'member:login' %}">Log In</a></li>
                {% endif %}
                <li><a href="{% url 'games:genres' %}">Genres</a></li>
                <li><a href = "{% url 'tags:view_all_tags'%}">Tags</a></li>
              </ul>
            </td>
          </tr>
        </table>
      </div>
    </header>
<div class = "mui-container">
<div class = "mui-panel">
<h1 > Games previously purchased: </h1>
{% if len < 1 %}
	<h2>No purchase records yet.</h2>
{% else %}

  {% for game in games %}
    <div class = "featured_games_item mui-panel">
        <div style = "float:left">
        <img src="{{ game.thumbnail.url }}" height="90" width="160">
        <h2><b>{{ game.get_genre_display }}</b> <a href="{% url 'games:game' game.id %}">{{ game.title }}</a></h2>
        <h3>{{ game.description }}</h3>
        <ul>
            {% for item in game.items.all %}
                <li>{{ item.get_platform_display }} - $ {{ item.price }}</li>
            {% endfor %}
        </ul>
        </div>
        <div>
        {% regroup game.tag_items.all|dictsort:'tag.label' by tag.label as tags %}
        {% for tag in tags %}
        <li class = "tagli" style = "display:inline">
            <a class="tagButton purchaseButton mui-btn mui-btn--primary mui-btn--raised" href="{% url 'tags:view_games_by_tag' tag.grouper %}">{{ tag.grouper }}</a></li>
        {% endfor %}
        </div>
    </div>
    {% endfor %}
  
{% endif %}
</div>
</div>
</body>


member/templates/member/signup.html
<h1>Sign Up</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Sign Up"/>
</form>
<br>
<p><strong>-- OR --</strong></p>
<a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>